Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'record'
      - 'records'
    Register: false
    Show-In-Help: true
    Priority: 30
    Condition: 'perm matrixshop.record.use'
    Help: |-
      <rainbow>==========&fRecord Help<rainbow>==========
      /ms {binding} help Open this help
      /ms {binding} open [keyword] Open the ledger
      /ms {binding} detail <id> Open one record detail
      /ms {binding} filter [module|all] Change the module filter
      /ms {binding} income | expense Open ledger statistics

View:
  Player:
    Show-Admin-Reason: true
