Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'record'
      - 'records'
    Register: false
    Show-In-Help: true
    Priority: 30
    Help-Key: '@commands.bindings.record'
    Hint-Keys:
      open: '@commands.bindings.record'
    Condition: 'perm matrixshop.record.use'

View:
  Player:
    Show-Admin-Reason: true
