Bindings:
  Commands:
    Bindings:
      - 'player_shop'
      - 'playershop'
      - 'pshop'
    Register: true
    Show-In-Help: true
    Priority: 100
    Condition: 'perm matrixshop.playershop.use'
    Help: |-
      <rainbow>==========&fPlayerShop Help<rainbow>==========
      /{binding} help Open this help
      /{binding} open [player] Open a player shop
      /{binding} edit Manage your player shop
      /{binding} upload <price> [amount] List the item in your hand
      /ms open {typed-id} Open this shop by typed id

Title:
  - '&8{owner} Shop &7{page}/{max-page}'

layout:
  - '#########'
  - '#ggggggg#'
  - '#ggggggg#'
  - '#ggggggg#'
  - '###I#E###'
  - 'P###B###N'

icons:
  '#':
    material: 'STAINED_GLASS_PANE'
    name: ' '
  'g':
    material: 'AIR'
    mode: 'goods'
  'I':
    material: 'PAPER'
    name: '&fShop Info'
    lore:
      - '&7Owner: &f{owner}'
      - '&7Listed: &f{listed}'
      - '&7Your Balance: &e{money}'
  'E':
    material: 'BOOK'
    name: '&eEdit My Shop'
    lore:
      - '&7Only visible for the owner'
      - '&eLeft click to open the edit view'
  'B':
    material: 'BARRIER'
    name: '&cClose'
    actions:
      left:
        - 'close'
  'P':
    material: 'ARROW'
    name: '&aPrevious'
  'N':
    material: 'ARROW'
    name: '&aNext'
