Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'player_shop'
      - 'playershop'
      - 'pshop'
    Register: false
    Show-In-Help: true
    Priority: 90
    Condition: 'perm matrixshop.playershop.use'

Unlock:
  Base: 21
  Max: 100

Listing:
  Tax:
    Enabled: false
    Mode: percent
    Value: 3.0
    # Rules:
    #   vip:
    #     Enabled: true
    #     Priority: 100
    #     Mode: percent
    #     Value: 1.0
    #     Condition:
    #       - "perm 'group.vip'"

Search:
  enable: true
  condition: "perm shop.vip"

Currency:
  Key: vault
