Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'player_shop'
      - 'playershop'
      - 'pshop'
    Register: false
    Show-In-Help: true
    Priority: 90
    Condition: 'perm matrixshop.playershop.use'
    Help: |-
      <rainbow>==========&fPlayerShop Help<rainbow>==========
      /ms {binding} help Open this help
      /ms {binding} open [player] Open a player shop
      /ms {binding} edit Manage your shop
      /ms {binding} upload <price> [amount] List the item in your hand

Unlock:
  Base: 21
  Max: 100

Search:
  enable: true
  condition: "perm shop.vip"
