Bindings:
  Commands:
    Bindings:
      - 'trade'
      - 'tm'
    Register: true
    Show-In-Help: true
    Priority: 100
    Help-Key: '@commands.bindings.transaction'
    Hint-Keys:
      open: '@commands.bindings.transaction'
      request: '@commands.hints.transaction-request'
      money: '@commands.hints.transaction-money'
      exp: '@commands.hints.transaction-exp'

Title:
  - '&8交易中心 &7{shop-id}'

layout:
  - '#########'
  - '###R#A###'
  - '#########'
  - '###L#####'
  - '#########'

icons:
  '#':
    material: 'STAINED_GLASS_PANE'
    name: ' '
  'R':
    material: 'NAME_TAG'
    name: '&a发起交易'
    lore:
      - '&7{hint-request} <player>'
  'A':
    material: 'EMERALD'
    name: '&f当前交易'
    lore:
      - '&7打开当前交易会话'
  'L':
    material: 'BOOK'
    name: '&6交易记录'
    lore:
      - '&7打开交易记录'
