Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'cart'
    Register: true
    Show-In-Help: true
    Priority: 40
    Help-Key: '@commands.bindings.cart'
    Hint-Keys:
      open: '@commands.bindings.cart'
      amount: '@commands.hints.cart-amount'
    Condition: 'perm matrixshop.cart.use'

Sources:
  Checkoutable:
    - system_shop
    - player_shop
    - global_market
  Auction:
    Enabled: true
    Type: watch_only
    Protected-On-Clear: true
