Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'menu'
      - 'menus'
    Register: false
    Show-In-Help: true
    Priority: 110
    Help-Key: '@commands.bindings.menu'
    Condition: 'perm matrixshop.menu.use'
