Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'auction'
      - 'ah'
    Register: true
    Show-In-Help: true
    Priority: 20
    Condition: 'perm matrixshop.auction.use'

Options:
  Currency:
    Key: vault
  Listing:
    Max-Active: 20
    Duration:
      Default: 86400
      Min: 600
      Max: 604800
    Modes:
      ENGLISH:
        Enabled: true
        Allow-Buyout: true
        Min-Start-Price: 100
        Min-Step:
          Mode: percent
          Fixed: 100
          Percent: 5
      DUTCH:
        Enabled: true
        Min-Start-Price: 100
        End-Price-Min: 1
        Tick-Seconds: 60
    Deposit:
      Enabled: true
      Mode: percent
      Value: 5
      Refund-On-Sell: true
      Refund-On-Cancel: false
    Tax:
      Enabled: true
      Mode: percent
      Value: 3
      # Rules:
      #   vip:
      #     Enabled: true
      #     Priority: 100
      #     Mode: percent
      #     Value: 1
      #     Condition:
      #       - "perm 'group.vip'"
  Snipe-Protection:
    Enabled: true
    Trigger-Seconds: 30
    Extend-Seconds: 30
    Max-Extend-Times: 5
  Cancel:
    Owner:
      Allow: true
      Deny-If-Has-Bid: true
  Record:
    Write-On-Create: true
    Write-On-Bid: false
    Write-On-Complete: true
    Write-On-Cancel: true
