Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'global_market'
      - 'globalmarket'
      - 'market'
      - 'gm'
    Register: false
    Show-In-Help: true
    Priority: 80
    Condition: 'perm matrixshop.globalmarket.use'

Listing:
  Expire-Hours: 72
  Tax:
    Enabled: true
    Mode: percent
    Value: 3.0
    # Rules:
    #   vip:
    #     Enabled: true
    #     Priority: 100
    #     Mode: percent
    #     Value: 1.0
    #     Condition:
    #       - "perm 'group.vip'"

Currency:
  Key: vault
