Enabled: true

Bindings:
  Commands:
    Bindings:
      - 'system'
      - 'systemshop'
    Register: false
    Show-In-Help: true
    Priority: 100
    Help-Key: '@commands.bindings.system-shop'
    Condition: 'perm matrixshop.systemshop.use'

Entry:
  Open-Main-On-Command: true

Currency:
  Default: vault
