Bindings:
  Commands:
    Bindings:
      - 'auction'
      - 'ah'
    Register: true
    Show-In-Help: true
    Priority: 100
    Condition: 'perm matrixshop.auction.use'
    Help: |-
      <rainbow>==========&fAuction Help<rainbow>==========
      /{binding} help Open this help
      /{binding} open Open this auction hall
      /{binding} upload <english|dutch> <start> [buyout|end] [duration] Upload the item in your hand
      /{binding} detail <id> Open one auction detail
      /{binding} bid <id> [price] Place a bid
      /ms open {typed-id} Open this auction hall by typed id

Title:
  - '&8Auction Hall &7{page}/{max-page}'

layout:
  - '#########'
  - '#ggggggg#'
  - '#ggggggg#'
  - '#ggggggg#'
  - '##U#B#M##'
  - 'P###R###N'

icons:
  '#':
    material: 'STAINED_GLASS_PANE'
    name: ' '
  'g':
    material: 'AIR'
    mode: 'goods'
  'U':
    material: 'CHEST'
    name: '&aUpload'
    lore:
      - '&7Open upload instructions'
  'B':
    material: 'GOLD_INGOT'
    name: '&6My Bids'
    lore:
      - '&7View auctions you have bid on'
  'M':
    material: 'BOOK'
    name: '&fMy Auctions'
    lore:
      - '&7Manage your active listings'
  'R':
    material: 'BARRIER'
    name: '&cClose'
    actions:
      left:
        - 'close'
  'P':
    material: 'ARROW'
    name: '&aPrevious'
  'N':
    material: 'ARROW'
    name: '&aNext'
